export const movies = [
    {
      id: '1',
      authorName: 'Andrzej Wajda',
      title: 'Ashes and Diamonds',
      description: 'A Polish resistance fighter faces moral dilemmas at the end of World War II.',
      rating: 8.2,
    },
    {
      id: '2',
      authorName: 'Roman Polanski',
      title: 'Knife in the Water',
      description: 'A tense psychological thriller set on a sailboat.',
      rating: 7.6,
    },
    {
      id: '3',
      authorName: 'Krzysztof Kieślowski',
      title: 'The Double Life of Véronique',
      description: 'A mysterious and lyrical tale of two women leading parallel lives.',
      rating: 7.8,
    },
    {
      id: '4',
      authorName: 'Paweł Pawlikowski',
      title: 'Ida',
      description: 'A young nun in 1960s Poland discovers a dark family secret.',
      rating: 7.4,
    },
    {
      id: '5',
      authorName: 'Agnieszka Holland',
      title: 'Europa Europa',
      description: 'A Jewish boy in Nazi Germany disguises himself as a member of the Hitler Youth.',
      rating: 7.6,
    },
    {
      id: '6',
      authorName: 'Wojciech Smarzowski',
      title: 'The Wedding',
      description: 'A dark comedy exposing the corruption and greed in Polish society.',
      rating: 7.0,
    },
    {
      id: '7',
      authorName: 'Jerzy Kawalerowicz',
      title: 'Mother Joan of the Angels',
      description: 'A haunting tale of demonic possession in a 17th-century convent.',
      rating: 7.5,
    },
    {
      id: '8',
      authorName: 'Andrzej Munk',
      title: 'Eroica',
      description: 'A satirical look at heroism during World War II.',
      rating: 7.3,
    },
    {
      id: '9',
      authorName: 'Krzysztof Kieślowski',
      title: 'Dekalog',
      description: 'A series of ten films exploring the Ten Commandments in modern society.',
      rating: 8.9,
    },
    {
      id: '10',
      authorName: 'Andrzej Wajda',
      title: 'Man of Marble',
      description: 'A young filmmaker investigates the rise and fall of a socialist hero.',
      rating: 7.8,
    },
    {
      id: '11',
      authorName: 'Steven Spielberg',
      title: 'Schindler\'s List',
      description: 'The true story of a man who saved over a thousand Jews during the Holocaust.',
      rating: 8.9,
    },
    {
      id: '12',
      authorName: 'Francis Ford Coppola',
      title: 'The Godfather',
      description: 'The aging patriarch of an organized crime dynasty transfers control to his reluctant son.',
      rating: 9.2,
    },
    {
      id: '13',
      authorName: 'Christopher Nolan',
      title: 'Inception',
      description: 'A thief who steals corporate secrets through dream-sharing technology is given a chance to have his criminal history erased.',
      rating: 8.8,
    },
    {
      id: '14',
      authorName: 'Quentin Tarantino',
      title: 'Pulp Fiction',
      description: 'The lives of two mob hitmen, a boxer, and a pair of diner bandits intertwine in four tales of violence and redemption.',
      rating: 8.9,
    },
    {
      id: '15',
      authorName: 'Peter Jackson',
      title: 'The Lord of the Rings: The Return of the King',
      description: 'The final confrontation between the forces of good and evil fighting for control of Middle-earth.',
      rating: 8.9,
    },
    {
      id: '16',
      authorName: 'David Fincher',
      title: 'Fight Club',
      description: 'An insomniac office worker forms an underground fight club as a form of male bonding.',
      rating: 8.8,
    },
    {
      id: '17',
      authorName: 'Martin Scorsese',
      title: 'Goodfellas',
      description: 'The story of Henry Hill and his life in the mob, covering his relationship with his wife and his partners in crime.',
      rating: 8.7,
    },
    {
      id: '18',
      authorName: 'Ridley Scott',
      title: 'Gladiator',
      description: 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
      rating: 8.5,
    },
    {
      id: '19',
      authorName: 'James Cameron',
      title: 'Titanic',
      description: 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.',
      rating: 7.8,
    },
    {
      id: '20',
      authorName: 'Robert Zemeckis',
      title: 'Forrest Gump',
      description: 'The presidencies of Kennedy and Johnson, the Vietnam War, and other historical events unfold from the perspective of an Alabama man with an IQ of 75.',
      rating: 8.8,
    },
    {
      id: '21',
      authorName: 'George Lucas',
      title: 'Star Wars: Episode IV - A New Hope',
      description: 'Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee, and two droids to save the galaxy from the Empire\'s world-destroying battle station.',
      rating: 8.6,
    },
    {
      id: '22',
      authorName: 'Alfred Hitchcock',
      title: 'Psycho',
      description: 'A Phoenix secretary embezzles $40,000 from her employer\'s client, goes on the run, and checks into a remote motel run by a young man under the domination of his mother.',
      rating: 8.5,
    },
    {
      id: '23',
      authorName: 'Stanley Kubrick',
      title: 'The Shining',
      description: 'A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence.',
      rating: 8.4,
    },
    {
      id: '24',
      authorName: 'Francis Ford Coppola',
      title: 'Apocalypse Now',
      description: 'A U.S. Army officer is sent on a mission to assassinate a renegade Special Forces Colonel who sees himself as a god.',
      rating: 8.4,
    },
];
   
  